# Generated by Django 2.2.6 on 2019-10-28 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='No',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_migration', models.DateTimeField()),
                ('perda_mdn', models.DecimalField(decimal_places=20, max_digits=50)),
                ('lat_min', models.DecimalField(decimal_places=20, max_digits=50)),
                ('lat_med', models.DecimalField(decimal_places=20, max_digits=50)),
                ('lat_max', models.DecimalField(decimal_places=20, max_digits=50)),
                ('std_dvn', models.DecimalField(decimal_places=20, max_digits=50)),
                ('lat_ten_perc', models.DecimalField(decimal_places=20, max_digits=50)),
                ('lat_mdn', models.DecimalField(decimal_places=20, max_digits=50)),
                ('lat_nine_perc', models.DecimalField(decimal_places=20, max_digits=50)),
                ('pop_dest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pop_dest_estado', to='rotas.Estado')),
                ('pop_env', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pop_env_estado', to='rotas.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Ligacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_ativo', models.BooleanField(default=True)),
                ('destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destino_estado', to='rotas.Estado')),
                ('origem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origem_estado', to='rotas.Estado')),
            ],
        ),
    ]
